-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "HDMI-A-1", mode = "2560x1440@144.000", position = "1920x0", scale = 1, vrr = 1 })
hl.monitor({ output = "eDP-1", mode = "1920x1080@144.003", position = "0x360", scale = 1, vrr = 1 })
