[Downloads]
disable_runtime_download = False
economy_mode = False
download_wine_to_steam = False
auto_download_ppdb = True
auto_appimage_updates = True

[Application]
version = 1.3.2

[Display]
fullscreen = False
tray_menu_mode = compact
auto_fullscreen_gamepad = False
minimize_to_tray = False
autostart_enabled = False
start_minimized = False

[Appearance]
theme = standart
theme_variant = auto
card_width = 250
auto_card_width = 250
badge_view_mode = detailed
hide_autoinstall_tab = False
enable_theme_store = False
theme_store_card_width = 350

[Gamepad]
type = auto

[PortProton]
portdata_path = /home/adachip/PortProtonQt

[Time]
detail_level = detailed

[Games]
sort_method = last_launch
display_filter = all

[Proxy]
proxy_url = 
proxy_user = 
proxy_password = 

[MainWindow]
width = 1272
height = 1364

