palette = "noctalia"
# ~/.config/starship.toml

# Get a clean, two-line prompt layout
format = """
| $os$username$hostname | $directory$git_branch$git_status
[➛](bold magenta) $character
"""

# Drop the right prompt to keep things lightweight
right_format = """"""

[character]
success_symbol = "[𖦹](bold cyan)"
error_symbol = "[✕](bold red)"

[username]
show_always = true
style_user = "fg:#bb9af7 bold"
style_root = "fg:#f7768e bold"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "fg:#7aa2f7 bold"
format = "@[$hostname]($style)"

[directory]
style = "fg:#73daca"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "fg:#ff007c"
format = "on [$symbol$branch]($style) "

[git_status]
style = "fg:#f7768e"
format = '([$all_status$ahead_behind]($style))'
conflicted = "⚑ "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕ "
untracked = "?${count} "
stashed = "📦 "
modified = "!${count} "
staged = "+${count} "
renamed = "» "
deleted = "✘ "

[cmd_duration]
min_time = 500
style = "fg:#e0af68"
format = "took [$duration]($style) "

[os]
disabled = false
style = "fg:#7aa2f7"

[os.symbols]
Linux = " "     # Bedrock Linux genellikle buraya düşer
Arch = " "   # Eğer Linux olarak da tanımazsa buraya düşer
Macos = "🍎 "
Windows = "   "

# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#b166e1"
red       = "#c46974"
green     = "#6798e4"
yellow    = "#7c71ed"
cyan      = "#9d94ea"
magenta   = "#93b6ec"
white     = "#f2f2f3"
black     = "#0d2344"

# Extended palette (Catppuccin-compatible names)
rosewater = "#7c71ed"
flamingo  = "#c46974"
pink      = "#93b6ec"
mauve     = "#93b6ec"
maroon    = "#c46974"
peach     = "#7c71ed"
teal      = "#9d94ea"
sky       = "#9d94ea"
sapphire  = "#b166e1"
lavender  = "#93b6ec"

# Text shades
text      = "#f2f2f3"
subtext1  = "#f2f2f3"
subtext0  = "#60666f"

# Surface shades
overlay2  = "#60666f"
overlay1  = "#60666f"
overlay0  = "#0d2344"
surface2  = "#0d2344"
surface1  = "#0d2344"
surface0  = "#0a1a33"
base      = "#0a1a33"
mantle    = "#0a1a33"
crust     = "#0a1a33"
# <<< NOCTALIA STARSHIP PALETTE <<<
