cursor #dde4e5
cursor_text_color #bbc9cc

foreground            #dde4e5
background            #0e1416
selection_foreground  #00363e
selection_background  #9dcfda
url_color             #89ebff

color0   #0e1416
color1   #ff72a2
color2   #7fff8c
color3   #fff572
color4   #6bdbf2
color5   #116576
color6   #89ebff
color7   #effcff
color8   #99a3a5
color9   #ff9fbf
color10  #a5ffae
color11  #fff9a5
color12  #9aeeff
color13  #acf1ff
color14  #c9f6ff
color15  #f8fdff
