# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x11122dff
rootcolor = 0x11122dff
bordercolor = 0x606270ff
dropcolor = 0x676ee480
splitcolor = 0xc666ccff
focuscolor = 0x676ee4ff
maximizescreencolor = 0x925cd6ff
urgentcolor = 0xfd4663ff
scratchpadcolor = 0xc666ccff
globalcolor = 0x0c138dff
overlaycolor = 0x3a106fff
jump_label_decorate_fg_color = 0xf2f2f3ff
jump_label_decorate_bg_color = 0x191b43ff
jump_label_decorate_focus_fg_color = 0x0d0e1aff
jump_label_decorate_focus_bg_color = 0x676ee4ff
jump_label_decorate_border_color = 0x606270ff
group_bar_decorate_fg_color = 0xf2f2f3ff
group_bar_decorate_bg_color = 0x191b43ff
group_bar_decorate_focus_fg_color = 0x0d0e1aff
group_bar_decorate_focus_bg_color = 0x676ee4ff
group_bar_decorate_border_color = 0x606270ff
