color0 #16183c
color1 #fd4663
color2 #6a72e8
color3 #9963dd
color4 #c666cc
color5 #9398ec
color6 #ba96e9
color7 #f2f2f3
color8 #606270
color9 #fd4663
color10 #6a72e8
color11 #9963dd
color12 #c666cc
color13 #9398ec
color14 #ba96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #11122d
background            #11122d
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #16183c
active_border_color   #676ee4
inactive_border_color #16183c
url_color             #676ee4

active_tab_foreground   #0d0e1a
active_tab_background   #676ee4
inactive_tab_foreground #afafb6
inactive_tab_background #16183c
cursor_trail_color      #afafb6
