# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Calamares packages configuration for Kyon Linux
---
backend: pacman

skip_if_no_internet: false
update_db: true
update_system: false

pacman:
    num_retries: 3
    disable_download_timeout: false
    needed_only: true

operations:
  - install:
    - neovim
    - nix
    - firefox
    - kitty
    - alacritty
    - git
    - fastfetch
    - networkmanager
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - wireplumber
    - flatpak