# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for the low-density software chooser
---
mode: required

method: netinstall-select

labels:
    step: "Desktop"
    step[tr]: "Masaüstü"

default: "KDE-Desktop"

items:
    - id: ""
      name: "No Desktop"
      name[tr]: "Masaüstü Yok"
      description: "Please pick a desktop environment from the list. If you don't want to install a desktop, that's fine, your system will start up in text-only mode."
      screenshot: ":/images/no-selection.png"

    - id: "Hyprland + DMS"
      name: "Hyprland + DMS"
      description: "Hyprland dynamic tiling Wayland compositor configured with Dank Material Shell. Slick, fast, and modern."
      screenshot: "/etc/calamares/images/hyprland.webp"

    - id: "Niri + DMS"
      name: "Niri + DMS"
      description: "Niri scrollable-tiling Wayland compositor configured with Dank Material Shell. Endless horizontal scrolling."
      screenshot: "/etc/calamares/images/niri.webp"

    - id: "KDE-Desktop"
      name: "Plasma Desktop"
      description: "KDE-Plasma Desktop - Simple by default, powerful when needed."
      screenshot: "/etc/calamares/images/kde.png"

    - id: "GNOME-Desktop"
      name: "GNOME"
      description: "Get things done with ease, comfort, and control."
      screenshot: "/etc/calamares/images/gnome.webp"

    - id: "i3 (x11)"
      name: "i3 (x11)"
      description: "i3 is a lightweight tiling window manager (x11) (might have bugs)"
      screenshot: "/etc/calamares/images/i3.jxl"

    - id: "Xfce4 (x11)"
      name: "Xfce4 (x11)"
      description: "Xfce is a lightweight and fast desktop environment. (x11)"
      screenshot: "/etc/calamares/images/xfce.jxl"

    - id: "LXQt (x11)"
      name: "LXQt (x11)"
      description: "Lightweight Qt-based desktop environment that keeps resource usage incredibly low (x11)"
      screenshot: "/etc/calamares/images/lxqt.jxl"

    - id: "LXDE (x11)"
      name: "LXDE (xqq)"
      description: "Classic ultra lightweight GTK desktop environment designed for absolute potato PCs (x11)"
      screenshot: "/etc/calamares/images/lxde.jxl"