# /etc/calamares/modules/shellprocess_dms.conf
---
dontChroot: false
timeout: 120
i18n:
  name: "Configuring Greeters"

script:
  - "if [ -f /usr/bin/dms ] && [ -f /usr/bin/niri ]; then dms greeter install && dms greeter enable; fi"
  - "if [ -f /usr/bin/noctalia-greeter ] && [ -f /usr/bin/hyprland ]; then noctalia-greeter install && noctalia-greeter enable; fi"
