---
dontChroot: false
timeout: 3600
script:
    - "pacman -Sy --noconfirm"
    - "-rm /etc/systemd/system/etc-pacman.d-gnupg.mount"
    - command: 'echo ""'  # Fixed nested quotes
    - "echo "
    - "echo "
    - '-runuser ${USER} -c "cp -rf /etc/skel/. /home/${USER}/."'
    - '-runuser ${USER} -c "rm -rf /home/${USER}/{.xsession,.xprofile,.xinitrc}"'
    - command: "bash /etc/calamares/scripts/shell-setup ${USER}"
      verbose: true
    - '-rm /etc/calamares/scripts/shell-setup'
    # Fixed the variable pointer below to use packagechooser_bootloader
    - command: "bash /etc/calamares/scripts/bootloader-post-setup ${gs[packagechooser_bootloader]}"
