# /etc/calamares/modules/shellprocess_dms.conf
---
dontChroot: false
timeout: 120
i18n:
    name: "Configuring DMS Greeter"

script:
    - "if [ -f /usr/bin/dms ] && ( [ -f /usr/bin/hyprland ] || [ -f /usr/bin/niri ] ); then dms greeter install && dms greeter enable; fi"